version: '3.3'
 
services:
  db:
    image: postgres:11
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgres/data
      - type: bind
        source: ./starter.sql
        target: /docker-entrypoint-initdb.d/starter.sql
    restart: always
      - POSTGRES_USER=aladár
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"
volumes:
  db_data:
