version: '3.3'

services:
  db:
    image: postgres:11
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgres/data
      - type: bind
        source: /home/ellenszenves/starter.sql
        target: /docker-entrypoint-initdb.d/starter.sql
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=shop
    ports:
      - "5432:5432"
volumes:
  db_data: